#!/usr/bin/env node
/* prose-guard.mjs — verify a PROSE-ONLY pass touched no load-bearing markup.
 *
 * The prose-expansion pass (every room → ~3 exploring paragraphs) must add/grow
 * ONLY narrative prose lines. Every line that carries game logic — a macro
 * (<<...>>), a link/target ([[...]] or the <<link>>/<<goto>> inside one), an NPC
 * <<linkreplace>> block, a passage header (:: Name) — is LOAD-BEARING and must
 * survive the pass byte-for-byte. This guard extracts, per file, the ordered
 * sequence of "control lines" (any line containing << >> [[ ]], or starting ::)
 * from git HEAD and from the working tree, and asserts they are IDENTICAL.
 *
 * Adding pure-prose lines never changes the control-line sequence, so a clean
 * run proves the agents only wrote prose. ANY divergence = a macro/link/header
 * was added, removed, reordered, or edited — reject that file and re-run it.
 *
 * Usage:  node tools/prose-guard.mjs            (compare working tree vs HEAD)
 *         node tools/prose-guard.mjs <ref>      (compare vs an arbitrary git ref)
 * Exit 0 = every file's control lines unchanged.  Exit 1 = a divergence (real bug).
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const ref = process.argv[2] || "HEAD";
const SRC = "src";
const SKIP = new Set(["map-data.twee"]); // generated by build.ps1 — not hand-prose

// A "control line" carries game logic/structure: any macro, link, or passage
// header. EXCEPTION: a line that is SOLELY a formatting macro (<<nobr>>,
// <<silently>> and their closers) is a rendering hint, not logic — splitting one
// flowing paragraph into two legitimately adds/removes such a standalone tag, so
// these are excluded from the byte-identical comparison. (A nobr tag sharing a
// line with any other markup is NOT exempt — it still compares.)
const FORMAT_ONLY = /^\s*<<\/?(nobr|silently)>>\s*$/;
const isControl = (line) =>
  !FORMAT_ONLY.test(line) && (/<<|>>|\[\[|\]\]/.test(line) || /^::\s/.test(line));

// Tag each control line with the passage it sits under, for localized reporting.
function controlLines(text) {
  const out = [];
  let passage = "(file head)";
  for (const raw of text.split(/\r?\n/)) {
    if (/^::\s/.test(raw)) passage = raw.replace(/^::\s+/, "").split("[")[0].split("{")[0].trim();
    if (isControl(raw)) out.push({ passage, line: raw.replace(/\r$/, "") });
  }
  return out;
}

function headText(file) {
  try {
    return execSync(`git show ${ref}:${SRC}/${file}`, { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] });
  } catch {
    return null; // new file (no HEAD version) — nothing to guard against
  }
}

const files = fs.readdirSync(SRC).filter((f) => f.endsWith(".twee") && !SKIP.has(f));
let bad = 0;
let checked = 0;

for (const file of files) {
  const head = headText(file);
  if (head == null) {
    console.log(`  ~ ${file}: new file (no ${ref} baseline) — skipped`);
    continue;
  }
  const work = fs.readFileSync(path.join(SRC, file), "utf8");
  const a = controlLines(head);
  const b = controlLines(work);
  checked++;

  if (a.length !== b.length) {
    bad++;
    console.log(`\n✗ ${file}: control-line COUNT changed (${a.length} → ${b.length}) — a macro/link/header was added or removed.`);
    // show the first divergence for localization
    const n = Math.min(a.length, b.length);
    for (let i = 0; i < n; i++) {
      if (a[i].line !== b[i].line) {
        console.log(`    first divergence near [${b[i].passage}]:`);
        console.log(`      HEAD: ${a[i].line.trim()}`);
        console.log(`      WORK: ${b[i].line.trim()}`);
        break;
      }
    }
    continue;
  }

  let fileBad = 0;
  for (let i = 0; i < a.length; i++) {
    if (a[i].line !== b[i].line) {
      if (fileBad === 0) console.log(`\n✗ ${file}: control line(s) EDITED — markup must be byte-identical:`);
      fileBad++;
      console.log(`    [${b[i].passage}]`);
      console.log(`      HEAD: ${a[i].line.trim()}`);
      console.log(`      WORK: ${b[i].line.trim()}`);
    }
  }
  if (fileBad) bad++;
  else console.log(`  ✓ ${file}: ${a.length} control lines intact`);
}

console.log(`\n${bad ? "✗" : "✓"} prose-guard: ${checked} files checked, ${bad} with markup divergence.`);
process.exit(bad ? 1 : 0);
